---
- hosts: master
  become: true
  tasks:
    - name: Add Jenkins GPG key to APT keyring
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository and GPG key
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present


    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install java
      apt:
        name: openjdk-17-jre
        state: present

    - name: install jenkins
      apt:
        name: jenkins
        state: present

    - name: start jenkins master service
      service:
        name: jenkins
        state: started

    - name: reboot enable service jenkins
      service:
        name: jenkins
        enabled: yes